# Generated by Django 3.1.5 on 2021-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEDS',
            fields=[
                ('location', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=255)),
                ('session_keys', models.TextField(blank=True)),
                ('timeout', models.DateTimeField(blank=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'leds',
                'managed': False,
            },
        ),
    ]
